### ISSUE TITLE
Catracoin  Site is down 

### ISSUE THREAD

**Issue by Thomasmcdaniel9** [catracoin/catracoin#1]
catracoin not sure whats up with your site but cant get any info on this coin from your whitepaper or anything. Are you going to peruse this idea or do away with it

**Comment by catracoin** [comment]
Hello,

thanks for your interest in the project, at the moment we are in a construction stage for this reason even our website is offline.

**Comment by Thomasmcdaniel9** [comment]
Ok great thanks for the response I'm interest in this project
